### ISSUE TITLE
crypto/batch: SupportsBatchVerifier should check if crypto.PubKey is non-nil before dereference

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#1825]
## Bug Report
While conducting a security audit and bug finding, I found this panic: if we run this code:
```go
package types_test

import (
	"testing"

	"github.com/cometbft/cometbft/types"
)

func TestReproVerifyCommit(t *testing.T) {
	vs := &types.ValidatorSet{
		Validators: []*types.Validator{{}, {}},
	}
	commit := &types.Commit{
		Height:     100,
		Signatures: []types.CommitSig{{}, {}},
	}
	var bid types.BlockID
	_ = vs.VerifyCommit("", bid, 100, commit)
}
```

we get this panic

```shell
--- FAIL: TestReproVerifyCommit (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x178dee6]

goroutine 6 [running]:
testing.tRunner.func1.2({0x1a5b680, 0x2029470})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1634 +0x377
panic({0x1a5b680?, 0x2029470?})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:770 +0x132
github.com/cometbft/cometbft/crypto/batch.SupportsBatchVerifier(...)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/crypto/batch/batch.go:26
github.com/cometbft/cometbft/types.shouldBatchVerify(0x0?, 0x0?)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:16 +0x26
github.com/cometbft/cometbft/types.VerifyCommit({0x0, 0x0}, 0xc0000fdf38, {{0x0, 0x0, 0x0}, {0x0, {0x0, 0x0, 0x0}}}, ...)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:44 +0xa8
github.com/cometbft/cometbft/types.(*ValidatorSet).VerifyCommit(...)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validator_set.go:663
github.com/cometbft/cometbft/types_test.TestReproVerifyCommit(0xc0003c4340?)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/repro_test.go:18 +0x11f
testing.tRunner(0xc0003c4340, 0x1b2c318)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1742 +0x390
exit status 2
FAIL	github.com/cometbft/cometbft/types	0.486s
```

### Setup
It stems from this https://github.com/cometbft/cometbft/blob/437391a0cb766ec0e7a2d87242a90b271ac31707/crypto/batch/batch.go#L25-L26

The fix for it is checking if the public key is non-nil so
```diff
diff --git a/crypto/batch/batch.go b/crypto/batch/batch.go
index 7587bc711..8ca5371ef 100644
--- a/crypto/batch/batch.go
+++ b/crypto/batch/batch.go
@@ -23,6 +23,10 @@ func CreateBatchVerifier(pk crypto.PubKey) (crypto.BatchVerifier, bool) {
 // SupportsBatchVerifier checks if a key type implements the batch verifier
 // interface.
 func SupportsBatchVerifier(pk crypto.PubKey) bool {
+	if pk == nil {
+		return false
+	}
+
 	switch pk.Type() {
 	case ed25519.KeyType, sr25519.KeyType:
 		return true
```

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
83172f78d45e47a41281d6a935c6fbd3e79dbae8 

**Have you tried the latest version**: yes/no

/cc @elias-orijtech @thanethomson

**Comment by lasarojc** [comment]
Thanks, @odeke-em for pointing the issue.
I've opened PR #1855 to address this issue and also #1826. Besides the fixes and test you suggested, I added one more check and test and would appreciate your review.
If instead you wish to provide a PR yourself with similar contents, I will close my PR and merge yours once ready.

**Comment by odeke-em** [comment]
Thank you @lasarojc for the fixes, they look good to me!
