### ISSUE TITLE
panic: non-recoverable error when signing vote

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2357]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): v0.38.5

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): vega

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**node command runtime flags**:

### Config

https://download.mainnet.community/tmkms.tar.gz

### What happened?

Panic during the attempted upgrade.

### What did you expect to happen?

No panic.

### How to reproduce it

https://download.mainnet.community/tmkms.tar.gz

### Logs

```
 2024-02-15T10:55:54.568Z	INFO	tendermint	pex/addrbook.go:545	new bucket is full, expiring new
 2024-02-15T10:55:54.772Z	INFO	tendermint	privval/signer_listener_endpoint.go:143	SignerListener: Blocking for connection
 2024-02-15T10:55:54.773Z	INFO	tendermint	privval/signer_listener_endpoint.go:159	SignerListener: Listening for new connection
 2024-02-15T10:55:55.458Z	INFO	tendermint	privval/signer_listener_endpoint.go:187	SignerListener: Connected
 panic: non-recoverable error when signing vote (20072402/1)

 goroutine 279 [running]:
 github.com/cometbft/cometbft/consensus.(*State).signVote(0xc001d12380, 0x2, {0xc0069c3920, 0x20, 0x20}, {0xd8a11c?, {0xc0069c3940?, 0xc0060fc704?, 0x37239c0?}}, 0xc0020fed20)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2388 +0x639
 github.com/cometbft/cometbft/consensus.(*State).signAddVote(0xc001d12380, 0x1?, {0xc0069c3920, 0x20, 0x20}, {0x1?, {0xc0069c3940?, 0xc000bccd40?, 0x20?}}, 0xc0020fed20)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2439 +0x212
 github.com/cometbft/cometbft/consensus.(*State).enterPrecommit(0xc001d12380, 0x13247d2, 0x1)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1536 +0x1337
 github.com/cometbft/cometbft/consensus.(*State).addVote(0xc001d12380, 0xc006b12b60, {0xc006723c20, 0x28})
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2296 +0x186f
 github.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc001d12380, 0xc006b12b60, {0xc006723c20?, 0x0?})
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x26
 github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc001d12380, {{0x440e4c0, 0xc0062ff978}, {0xc006723c20, 0x28}})
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce
 github.com/cometbft/cometbft/consensus.(*State).readReplayMessage(0xc001d12380, 0x3cfaf18?, {0x0?, 0x0?})
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:82 +0x918
 github.com/cometbft/cometbft/consensus.(*State).catchupReplay(0xc001d12380, 0x13247d2)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:161 +0x6dd
 github.com/cometbft/cometbft/consensus.(*State).OnStart(0xc001d12380)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:342 +0x165
 github.com/cometbft/cometbft/libs/service.(*BaseService).Start(0xc001d12380)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/libs/service/service.go:144 +0x2f5
 github.com/cometbft/cometbft/consensus.(*Reactor).SwitchToConsensus(_, {{{0xb, 0x1}, {0xc001a4f830, 0x7}}, {0xc002b695c0, 0x14}, 0x1, 0x13247d1, {{0xc000bccd40, ...}, ...}, ...}, ...)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/reactor.go:131 +0xb9
 github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc001973e00, 0x0)
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/blocksync/reactor.go:406 +0xf34
 github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart.func1()
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/blocksync/reactor.go:129 +0x54
 created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 197
 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/blocksync/reactor.go:127 +0x8b
```

**Comment by melekes** [comment]
Refs https://github.com/iqlusioninc/tmkms/issues/831#issuecomment-1948384671

**Comment by melekes** [comment]
Opened https://github.com/iqlusioninc/tmkms/pull/857

**Comment by melekes** [comment]
Closing since it's not a CometBFT issue.
