### ISSUE TITLE
types: VerifyCommit* method should validate firstly that the validator set has a non-nil proposer and non-nil public key lest a runtime nil panic

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#2625]
## Bug Report
I found this bug by fuzzing VerifyCommitLightTrust with this minimized reproduction

```go
func TestReproBugLightTrusting(t *testing.T) {
        vs := &types.ValidatorSet{
                Validators: []*types.Validator{{}, {}},
        }
        commit := &types.Commit{
                Height:     100,
                Signatures: []types.CommitSig{{}, {}},
        }
        _ = vs.VerifyCommitLightTrusting("chain_id", commit, tmmath.Fraction{2, 3})
}
```

which produces

```shell
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xea3b3c6]

goroutine 8 [running]:
testing.tRunner.func1.2({0xefcd680, 0xf6d2cd0})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1634 +0x377
panic({0xefcd680?, 0xf6d2cd0?})
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:759 +0x132
github.com/tendermint/tendermint/crypto/batch.SupportsBatchVerifier(...)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/crypto/batch/batch.go:27
github.com/tendermint/tendermint/types.shouldBatchVerify(0xc0004def28?, 0xf6f9820?)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:15 +0xf
github.com/tendermint/tendermint/types.VerifyCommitLightTrusting({0xec181c2, 0x8}, 0xc0000a7f28, 0xc0000a7ea0, {0xf2631ba?, 0x49?})
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:128 +0x125
github.com/tendermint/tendermint/types.(*ValidatorSet).VerifyCommitLightTrusting(...)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validator_set.go:670
github.com/tendermint/tendermint/types.TestReproBugLightTrusting(0xc0000b8820)
	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/fuzz_test.go:237 +0xeb
testing.tRunner(0xc0000b8820, 0xf0c9208)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1742 +0x390
exit status 2
FAIL	github.com/tendermint/tendermint/types	0.307s
```

The fix for this should be to at the very top verify that there is a non-nil proposer
```diff
diff --git a/types/validation.go b/types/validation.go
index 02d1b0b56..cccd48a67 100644
--- a/types/validation.go
+++ b/types/validation.go
@@ -104,6 +104,10 @@ func VerifyCommitLightTrusting(chainID string, vals *ValidatorSet, commit *Commi
 	if commit == nil {
 		return errors.New("nil commit")
 	}
+	proposer := vals.GetProposer()
+	if proposer == nil || proposer.PubKey == nil {
+		return errors.New("nil proposer.PubKey in validatorSet")
+	}
 
 	// safely calculate voting power needed.
 	totalVotingPowerMulByNumerator, overflow := safeMul(vals.TotalVotingPower(), int64(trustLevel.Numerator))
```

**Comment by melekes** [comment]
`VerifyCommitLightTrusting` is only called with a trusted validator set. Therefore, the checks you're suggesting are not necessary. Please let us know if you find similar vulnerabilities in `VerifyCommitLight` or `VerifyCommitLightAllSignatures`.
