### ISSUE TITLE
types: VerifyCommitLightTrusting should at the beginning simply invoke Commit.Block.ValidateBasic() and check that error long before invoking commit.VoteSignBytes

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#2627]
## Bug Report
Found through fuzzing, if there is a commit with a BlockID whose value is not 32-bytes e.g. `"F4D22138F431C3167CEE09EFE638B875timestF60A1442E6A603E7B8FF2CA561"`, deep within there will be a panic yet really before doing any work we should have validated that the BlockID was valid with this crash
```shell
esting.go:1590: panic: wrong Hash: expected size to be 32 bytes, got 48 bytes
            goroutine 10402 [running]:
            runtime/debug.Stack()
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/debug/stack.go:26 +0x9b
            testing.tRunner.func1()
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1590 +0x1c8
            panic({0x3a7da60?, 0xc00805b120?})
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:759 +0x132
            github.com/tendermint/tendermint/types.FuzzVerifyCommitLightTrusting.func1.1()
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/fuzz_test.go:217 +0x135
            panic({0x3a7da60?, 0xc00805b120?})
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:759 +0x132
            github.com/tendermint/tendermint/types.CanonicalizeBlockID({{0xc0083a4cf0, 0x30, 0x30}, {0x7b, {0xc00806d280, 0x20, 0x40}}})
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/canonical.go:21 +0x2c5
            github.com/tendermint/tendermint/types.CanonicalizeVote(...)
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/canonical.go:62
            github.com/tendermint/tendermint/types.VoteSignBytes({0xc0083a6580, 0xa}, 0xc006d712d8)
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/vote.go:150 +0x1b
            github.com/tendermint/tendermint/types.(*Commit).VoteSignBytes(0x3a6cee0?, {0xc0083a6580, 0xa}, 0x30?)
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/block.go:861 +0x299
            github.com/tendermint/tendermint/types.verifyCommitBatch({0xc0083a6580, 0xa}, 0xc0083a83f0, 0xc0002b0d80, 0xa6, 0x3b727c0, 0x3b727c8, 0x0, 0x0)
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:212 +0x4c5
            github.com/tendermint/tendermint/types.VerifyCommitLightTrusting({0xc0083a6580, 0xa}, 0xc0083a83f0, 0xc0002b0d80, {0xc0083927e0?, 0x4?})
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validation.go:129 +0x5a5
            github.com/tendermint/tendermint/types.(*ValidatorSet).VerifyCommitLightTrusting(...)
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/validator_set.go:670
            github.com/tendermint/tendermint/types.FuzzVerifyCommitLightTrusting.func1(0x0?, {0xc000880000, 0x13c0, 0x63fff9c})
            	/Users/emmanuelodeke/go/src/github.com/cometbft/cometbft/types/fuzz_test.go:225 +0xf3
            reflect.Value.call({0x3a430c0?, 0x3b72518?, 0x13?}, {0x36ac17d, 0x4}, {0xc0083a8390, 0x2, 0x2?})
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/reflect/value.go:587 +0xca6
            reflect.Value.Call({0x3a430c0?, 0x3b72518?, 0x29d650d?}, {0xc0083a8390?, 0x3b71120?, 0xf?})
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/reflect/value.go:371 +0xb9
            testing.(*F).Fuzz.func1.1(0xc008395040?)
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/fuzz.go:335 +0x325
            testing.tRunner(0xc008395040, 0xc0083aa360)
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1689 +0xfb
            created by testing.(*F).Fuzz.func1 in goroutine 7
            	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/fuzz.go:322 +0x574
```

## Fix
```diff
diff --git a/types/validation.go b/types/validation.go
index 02d1b0b56..c0b8cdc75 100644
--- a/types/validation.go
+++ b/types/validation.go
@@ -105,6 +105,16 @@ func VerifyCommitLightTrusting(chainID string, vals *ValidatorSet, commit *Commi
                return errors.New("nil commit")
        }
 
+       // Validate that the BlockID is valid before doing any work.
+       if err := commit.BlockID.ValidateBasic(); err != nil {
+               return err
+       }
+
+       proposer := vals.GetProposer()
+       if proposer == nil || proposer.PubKey == nil {
+               return errors.New("nil proposer.PubKey in validatorSet")
+       }
+
```

**Comment by melekes** [comment]
See https://github.com/cometbft/cometbft/pull/2662#issuecomment-2048998246
