### ISSUE TITLE
p2p/conn/secret_connection.go panic: `not a valid operation`

### ISSUE THREAD

**Issue by trinitys7** [cometbft/cometbft#3147]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
0.37.2
**Have you tried the latest version**: yes/no
no
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
cosmos-sdk
**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 20.04
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?
When running a node using custom cometbft. I realized the node sometimes panic: `not a valid operation`
When I check the code, it's due to [strobe repository](https://github.com/mimoo/StrobeGo/blob/122bf33a46e0266f0302903b543a9e3286f48703/strobe/strobe.go#L441)

The node panic multiple times, I tried debugging and come up with a result that operation "AD" in `operationMap` is always not catched right.

It's really weird because in here, `operationMap` is a pre defined map[string]uint64 variable:
https://github.com/mimoo/StrobeGo/blob/122bf33a46e0266f0302903b543a9e3286f48703/strobe/strobe.go#L267-L278
I even tried printing it. It show up that operationMap contains operation "AD" but operationMap["AD"] is nil.

### How to reproduce it
Disable apphash of the cometbft. Run node and make the node sync with other node. 

### Logs
```
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="dfde7db9813bd5d63b79e77e23dd8c531a4cac2b@72.46.84.137:14356"
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1152] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1152] bugsnag.Notify: not notifying in local       
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1152] notifying bugsnag: Stopping peer for error   
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1152] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1152] bugsnag.Notify: not notifying in local       
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="dfde7db9813bd5d63b79e77e23dd8c531a4cac2b@72.46.84.137:14356"
INFO[1152] bugsnag.Notify: not notifying in local       
ERRO[1152] Stopping peer for error                       err="unknown channel 22" module=p2p peer="Peer{MConn{162.19.222.253:26656} 877ce85fb9b203e2f7da5f0e268659dbe76eafe1 out}"
INFO[1152] service stop                                  fields.msg="Stopping Peer service" impl="Peer{MConn{162.19.222.253:26656} 877ce85fb9b203e2f7da5f0e268659dbe76eafe1 out}" module=p2p peer="877ce85fb9b203e2f7da5f0e268659dbe76eafe1@162.19.222.253:26656"
INFO[1152] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1152] bugsnag.Notify: not notifying in local       
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1152] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1152] bugsnag.Notify: not notifying in local       
ERRO[1152] Cannot send bytes, unknown channel 20         module=p2p peer="dfde7db9813bd5d63b79e77e23dd8c531a4cac2b@72.46.84.137:14356"
INFO[1153] service stop                                  fields.msg="Stopping MConnection service" impl="MConn{72.46.84.137:14356}" module=p2p peer="dfde7db9813bd5d63b79e77e23dd8c531a4cac2b@72.46.84.137:14356"
INFO[1153] notifying bugsnag: Stopping peer for error   
INFO[1153] bugsnag.Notify: not notifying in local       
ERRO[1153] Stopping peer for error                       err="unknown channel 20" module=p2p peer="Peer{MConn{72.46.84.137:14356} dfde7db9813bd5d63b79e77e23dd8c531a4cac2b out}"
INFO[1153] service stop                                  fields.msg="Stopping Peer service" impl="Peer{MConn{72.46.84.137:14356} dfde7db9813bd5d63b79e77e23dd8c531a4cac2b out}" module=p2p peer="dfde7db9813bd5d63b79e77e23dd8c531a4cac2b@72.46.84.137:14356"
INFO[1153] Timed out                                     dur=1s height=71942681 module=consensus round=0 step=RoundStepPrecommitWait
INFO[1153] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1153] bugsnag.Notify: not notifying in local       
ERRO[1153] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1153] notifying bugsnag: Cannot send bytes, unknown channel 20 
INFO[1153] bugsnag.Notify: not notifying in local       
ERRO[1153] Cannot send bytes, unknown channel 20         module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1155] service stop                                  fields.msg="Stopping MConnection service" impl="MConn{141.94.193.168:26656}" module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1155] notifying bugsnag: Stopping peer for error   
INFO[1155] bugsnag.Notify: not notifying in local       
ERRO[1155] Stopping peer for error                       err="unknown channel 20" module=p2p peer="Peer{MConn{141.94.193.168:26656} 68ed36be2c22c504d47b531421bc7be933eb0189 out}"
INFO[1155] service stop                                  fields.msg="Stopping Peer service" impl="Peer{MConn{141.94.193.168:26656} 68ed36be2c22c504d47b531421bc7be933eb0189 out}" module=p2p peer="68ed36be2c22c504d47b531421bc7be933eb0189@141.94.193.168:26656"
INFO[1157] Timed out                                     dur=3.5s height=71942681 module=consensus round=1 step=RoundStepPropose
INFO[1170] Ensure peers                                  module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
INFO[1200] Saving AddrBook to file                       book=/home/anhminh/.injectived/config/addrbook.json module=p2p size=1631
INFO[1200] Ensure peers                                  module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
panic: not a valid operation

goroutine 319214 [running]:
github.com/mimoo/StrobeGo/strobe.(*Strobe).Operate(0xc16da091c0, 0x1, {0x2fd6f72?, 0x0?}, {0x2fe4383, 0xb, 0x4147c5?}, 0x0, 0x0)
        /home/trinitys7/go/pkg/mod/github.com/mimoo/!strobe!go@v0.0.0-20210601165009-122bf33a46e0/strobe/strobe.go:441 +0x2de
github.com/mimoo/StrobeGo/strobe.InitStrobe({_, _}, _)
        /home/trinitys7/go/pkg/mod/github.com/mimoo/!strobe!go@v0.0.0-20210601165009-122bf33a46e0/strobe/strobe.go:344 +0x1f9
github.com/gtank/merlin.NewTranscript({0x306ad61, 0x2c})
        /home/trinitys7/go/pkg/mod/github.com/gtank/merlin@v0.1.1/merlin.go:20 +0x57
github.com/cometbft/cometbft/p2p/conn.MakeSecretConnection({0x7ea09827ca70, 0xc16bd0adf8}, {0x3ebc960, 0xc007512510})
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/conn/secret_connection.go:111 +0x106
github.com/cometbft/cometbft/p2p.upgradeSecretConn({0x3ecbfc8, 0xc16bd0adf8}, 0xb2d05e00, {0x3ebc960, 0xc007512510})
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/transport.go:586 +0xa5
github.com/cometbft/cometbft/p2p.(*MultiplexTransport).upgrade(0xc0029f3700, {0x3ecbfc8, 0xc16bd0adf8}, 0xc142a7df50)
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/transport.go:415 +0xeb
github.com/cometbft/cometbft/p2p.(*MultiplexTransport).Dial(0xc0029f3700, {{0xc0030fcea0, 0x28}, {0xc0033bba70, 0x10, 0x10}, 0x6820}, {{0xc001f6af80, 0xa, 0x10}, ...})
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/transport.go:225 +0x125
github.com/cometbft/cometbft/p2p.(*Switch).addOutboundPeerWithConfig(0xc000da25a0, 0xc002fdf5f0, 0xc0017a9200)
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/switch.go:738 +0x2fc
github.com/cometbft/cometbft/p2p.(*Switch).DialPeerWithAddress(0xc000da25a0, 0xc002fdf5f0)
        /home/trinitys7/go/pkg/mod/github.com/!dong!co!n!y/cometbft@v0.37.2-inj-1.test.disable.3/p2p/switch.go:557 +0x106
github.com/cometbft/cometbft/p2p/pex.(*Reactor).dialPeer(0xc001f73a40, 0xc002fdf5f0)
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/pex/pex_reactor.go:564 +0x1c5
github.com/cometbft/cometbft/p2p/pex.(*Reactor).ensurePeers.func1(0xc002fdf5f0)
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/pex/pex_reactor.go:499 +0x2b
created by github.com/cometbft/cometbft/p2p/pex.(*Reactor).ensurePeers in goroutine 116
        /home/trinitys7/go/pkg/mod/github.com/cometbft@v0.37.2-inj-1.test.disable.3/p2p/pex/pex_reactor.go:498 +0x3fe
```

**Comment by andynog** [comment]
Hi @trinitys7, thanks for reporting this. In order to understand the problem better, could you please provide additional details on how to reproduce it ? More precisely the steps you're doing to when you mentioned you disabled the apphash in CometBFT. Looks like you are also using the Cosmos SDK on your setup ?

**Comment by trinitys7** [comment]
@andynog Hi, yes i'm using cosmos sdk. So my purpose is changing the logic inside binary to make the node get more data. That's why I want to disable the app hash.

However, for now, I just commented the panic when checking app hash, not chaning anything else about binary and running the node to sync with others. I tried 2 chains using cosmos-sdk 47 and cometbft 0.37.2 (changed as above) and both of them come up with this issue after a few blocks. 

I'm kinda sure that my changes doesn't related to this issue, cause it happened in p2p.

**Comment by melekes** [comment]
Are you sure you're using vanilla CometBFT / Cosmos SDK?

`Cannot send bytes, unknown channel 20` means that p2p connection was not correctly constructed (we're creating multiple pseudo streams per one TCP connection and `20` is one of them, specifically consensus state).

**Comment by cason** [comment]
Hey, the logs are not really clear. Channel `20` is used by the consensus reactor:

https://github.com/cometbft/cometbft/blob/b4b1f9c42eca4bf775ab5ddb5d3915dd55004eb6/internal/consensus/reactor.go#L27

There is also a report regarding channel `22`, also used by consensus. The log errors are therefore because the consensus reactor is not registered (running) in the interested node.

**Comment by cason** [comment]
The reported panic is on the following line:

https://github.com/cometbft/cometbft/blob/2dd5209177270fde125c71aeedda9819046f92f0/p2p/conn/secret_connection.go#L106

Any chance you have changed the string used for the challenged between the two nodes?

**Comment by cason** [comment]
> When running a node using custom cometbft. 

What did you customize?

**Comment by adizere** [comment]
hi @trinitys7 is this still a relevant issue?

**Comment by trinitys7** [comment]
Hi  @cason @melekes  I know channel 20 is irrelevant issue, cause I customize the cometbft and something may be broke from it. But I don't think the issue `not a valid operation` caused by channel 20 problem. You can see from this line, I did not change anything with it but it still panic. That's why I raise the issue

> The reported panic is on the following line:
> 
> https://github.com/cometbft/cometbft/blob/2dd5209177270fde125c71aeedda9819046f92f0/p2p/conn/secret_connection.go#L106
> 
> Any chance you have changed the string used for the challenged between the two nodes?

**Comment by cason** [comment]
Hey, we would need a way to reproduce the bug: a test unit, a specific scenario we can reproduce, while using upstream code preferentially.

**Comment by cason** [comment]
Hi @trinitys7, did you find a way to reproduce this issue?

**Comment by sergio-mena** [comment]
@trinitys7 feel free to reopen with you manage to repro the problem
