### ISSUE TITLE
light: `runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [cometbft/cometbft#3992]
### Setup
I'm on commit  `3323096bbb87d8722402f0a62a94b94589483097`
Getting a `Nil Pointer Dereference Error` when hitting the /block endpoint. This is also happing with other endpoints as well.
I have two validating nodes running locally and started the light client with:
```bash
./cometbft light 3636 -p "tcp://127.0.0.1:26657" -w "tcp://127.0.0.1:36657"
```

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
cb31aae24cf96b0aef918bf926680a67ea15ca76

**Have you tried the latest version**: yes/no
yes
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Reth Eth client
**Environment**:
- **OS** (e.g. from /etc/os-release):
 Macos 14.5 (23F79)
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?
Nil derefrence exception
### What did you expect to happen?
Return the latest light block
### Logs

Logs: 
```
I[2024-09-03|19:54:39.677] deprecated usage found in configuration file usage="[consensus.timeout_commit] is deprecated. Use `next_block_delay` in the ABCI `FinalizeBlockResponse`."
I[2024-09-03|19:54:39.677] Creating client...                           chainID=3636
I[2024-09-03|19:54:40.037] Starting proxy...                            laddr=tcp://localhost:8888
I[2024-09-03|19:54:40.046] serve                                        msg="Starting RPC HTTP server on 127.0.0.1:8888"
I[2024-09-03|19:55:02.662] VerifyHeader                                 height=1 hash=A55330FD41FB11793B5A737D7D5B9236A13D03C024642C401CD35B9E245C98EC
E[2024-09-03|19:55:02.664] panic in RPC HTTP handler                    err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 10 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1.2()\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:214 +0x557\npanic({0x4fd06c0?, 0x599a7e0?})\n\truntime/panic.go:770 +0x132\ngithub.com/cometbft/cometbft/light.(*Client).verifyLightBlock(0xc00015e6c0, {0x5158838, 0xc000180230}, 0xc00004ecc0, {0x275c7e08?, 0xede696096?, 0x0?})\n\tgithub.com/cometbft/cometbft/light/client.go:581 +0x22a\ngithub.com/cometbft/cometbft/light.(*Client).VerifyLightBlockAtHeight(0xc00015e6c0, {0x5158838, 0xc000180230}, 0x1, {0xc000482840?, 0x20?, 0x0?})\n\tgithub.com/cometbft/cometbft/light/client.go:492 +0xda\ngithub.com/cometbft/cometbft/light/rpc.(*Client).updateLightClientIfNeededTo(0xc00026e380, {0x5158838, 0xc000180230}, 0xc0000f6040)\n\tgithub.com/cometbft/cometbft/light/rpc/client.go:566 +0x6e\ngithub.com/cometbft/cometbft/light/rpc.(*Client).Block(0xc00026e380, {0x5158838, 0xc000180230}, 0x4?)\n\tgithub.com/cometbft/cometbft/light/rpc/client.go:330 +0x218\ngithub.com/cometbft/cometbft/light/proxy.RPCRoutes.makeBlockFunc.func10(0x0?, 0xc0000126f0)\n\tgithub.com/cometbft/cometbft/light/proxy/routes.go:110 +0x3a\nreflect.Value.call({0x4fe0360?, 0xc0002ee2b0?, 0x5140a00?}, {0x4c2c256, 0x4}, {0xc00018d6e0, 0x2, 0x2?})\n\treflect/value.go:596 +0xca6\nreflect.Value.Call({0x4fe0360?, 0xc0002ee2b0?, 0x4c30d6a?}, {0xc00018d6e0?, 0x5140a00?, 0xc0004822e0?})\n\treflect/value.go:380 +0xb9\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeHTTPHandler.func2({0x5153550, 0xc0003021b0}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_uri_handler.go:60 +0x4c5\nnet/http.HandlerFunc.ServeHTTP(0xc0001108f0?, {0x5153550?, 0xc0003021b0?}, 0x4f7b280?)\n\tnet/http/server.go:2171 +0x29\nnet/http.(*ServeMux).ServeHTTP(0xd?, {0x5153550, 0xc0003021b0}, 0xc0003d45a0)\n\tnet/http/server.go:2688 +0x1ad\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.defaultHandler.ServeHTTP(...)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:262\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x51533f0, 0xc000398a80}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:237 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x514b718?, {0x51533f0?, 0xc000398a80?}, 0x4f53980?)\n\tnet/http/server.go:2171 +0x29\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.PreChecksHandler.func2({0x51533f0, 0xc000398a80}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:327 +0x10c\nnet/http.HandlerFunc.ServeHTTP(0x415ea99?, {0x51533f0?, 0xc000398a80?}, 0xc00017cb68?)\n\tnet/http/server.go:2171 +0x29\nnet/http.serverHandler.ServeHTTP({0xc00018d350?}, {0x51533f0?, 0xc000398a80?}, 0x6?)\n\tnet/http/server.go:3142 +0x8e\nnet/http.(*conn).serve(0xc0000d0090, {0x5158800, 0xc000473a40})\n\tnet/http/server.go:2044 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 1\n\tnet/http/server.go:3290 +0x4b4\n"

``` 

### `dump_consensus_state` output

```json
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "round_state": {
      "height": "2786",
      "round": 0,
      "step": 1,
      "start_time": "2024-09-03T20:00:05.85179Z",
      "commit_time": "2024-09-03T20:00:04.85179Z",
      "validators": {
        "validators": [
          {
            "address": "009D915D631DB0A3FEFB32685779D023153698DB",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
            },
            "voting_power": "10",
            "proposer_priority": "0"
          },
          {
            "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
            },
            "voting_power": "10",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
          },
          "voting_power": "10",
          "proposer_priority": "0"
        }
      },
      "proposal": null,
      "proposal_receive_time": "0001-01-01T00:00:00Z",
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": -1,
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": -1,
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": 0,
          "prevotes": [
            "nil-Vote",
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{2:__} 0/20 = 0.00",
          "precommits": [
            "nil-Vote",
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{2:__} 0/20 = 0.00"
        }
      ],
      "commit_round": -1,
      "last_commit": {
        "votes": [
          "Vote{0:009D915D631D 2785/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 60663836B00C A59A51ADA7DF B896886E109B @ 2024-09-03T20:00:04.830052Z}",
          "Vote{1:09784D2BAA50 2785/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 60663836B00C ADDF300C714D B896886E109B @ 2024-09-03T20:00:04.781122Z}"
        ],
        "votes_bit_array": "BA{2:xx} 20/20 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "009D915D631DB0A3FEFB32685779D023153698DB",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
            },
            "voting_power": "10",
            "proposer_priority": "-10"
          },
          {
            "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
            },
            "voting_power": "10",
            "proposer_priority": "10"
          }
        ],
        "proposer": {
          "address": "009D915D631DB0A3FEFB32685779D023153698DB",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
          },
          "voting_power": "10",
          "proposer_priority": "-10"
        }
      },
      "triggered_timeout_precommit": false
    },
    "peers": [
      {
        "node_address": "331616cba520bff2bcfa3efbe748a044d9ec3c08@127.0.0.1:36656",
        "peer_state": {
          "round_state": {
            "height": "2786",
            "round": 0,
            "step": 1,
            "start_time": "2024-09-03T20:00:05.044835Z",
            "proposal": false,
            "proposal_block_part_set_header": {
              "total": 0,
              "hash": ""
            },
            "proposal_block_parts": null,
            "proposal_pol_round": -1,
            "proposal_pol": "__",
            "prevotes": "__",
            "precommits": "__",
            "last_commit_round": 0,
            "last_commit": "xx",
            "catchup_commit_round": -1,
            "catchup_commit": "__"
          },
          "stats": {
            "votes": "580",
            "block_parts": "145"
          }
        }
      }
    ]
  }
}

```

**Comment by melekes** [comment]
Can we get the debug level logs? `./cometbft light 3636  --verbose -p "tcp://127.0.0.1:26657" -w "tcp://127.0.0.1:36657"`

**Comment by melekes** [comment]
Can you replicate this with an older version (e.g. [v1.0.0-rc1](https://github.com/cometbft/cometbft/releases/tag/v1.0.0-rc1))?

**Comment by melekes** [comment]
You need to initialize the light client with a trusted hash and height, for example:

```
--height=123 --hash=E7C95EBBC47415F936CD3E7167627F3078C75FE91712377B2308F5DC5312C8B5
```

**Comment by melekes** [comment]
We should return an error instead of panicking.

**Comment by cason** [comment]
I could observe the same error in previous executions.

It looks like mandatory to provide some initial information to a fresh light client, namely a trusted `height` and `hash`, from which it initializes its database.

I agree that we should not panic in this case, providing instead an useful error message for the user.

**Comment by cason** [comment]
Notice that the description of the `light` command contains:

```
Furthermore to the chainID, a fresh instance of a light client will
need a primary RPC address, a trusted hash and height and witness RPC addresses
(if not using sequential verification).
```

So it is mandatory to provide trusted information to boostrap a new light client, rendering the use case invalid. It should still not panic indeed.

**Comment by 0xBEEFCAF3** [comment]
Providing trusted height + hash ended up working as of 3323096bbb87d8722402f0a62a94b94589483097. 
Thanks for the help
