### ISSUE TITLE
CometBFT should notify upon fatal errors and ensure node termination

### ISSUE THREAD

**Issue by lucaslopezf** [cometbft/cometbft#4054]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
- v0.34.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
- Cosmos-SDK

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Install tools**: Docker, Kubernetes
- **Others**: N/A

### What happened?

When there is a failure in the consensus layer, such as during an upgrade that requires a binary update, CometBFT stops the blockchain, but Cosmos-SDK is never informed of this. This results in the node continuing to respond to queries with the blockchain halted.

In the case of a panic, the code enters this recover: [state.go#L812](https://github.com/cometbft/cometbft/blob/a170d312b28a429d1fecc32cd94d91b01c5ad8f7/internal/consensus/state.go#L812). As the function comment states, the intention is to stop the chain. However, there is no communication to Cosmos-SDK about this, and the `isRunning()` method ([service.go#L45](https://github.com/cometbft/cometbft/blob/5e4ab3c747558cdea85cdd3fc320fe6b5c363930/libs/service/service.go#L45)) still returns true.

This results in an inconsistency in the application, as described in the following issue:

- [Cosmos SDK Issue #20745](https://github.com/cosmos/cosmos-sdk/issues/20745)

### What did you expect to happen?

I expected CometBFT to notify Cosmos-SDK upon encountering a fatal error and ensure that the node terminates properly, reflecting the halted state accurately.

### How to reproduce it

1. Start a new node with `simd` in Cosmos.
2. Submit an upgrade proposal.
3. Vote on the proposal.
4. Once the proposal period has passed, observe the issue.

### Logs

```bash
3:39PM ERR CONSENSUS FAILURE!!! err="runtime error: invalid memory address or nil pointer dereference" module=consensus stack="goroutine 1069 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46\npanic({0x47077a0?, 0x75ae2c0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).FinalizeBlock.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.50.4/baseapp/abci.go:893 +0x16a\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).FinalizeBlock(0xc0012866c0, 0xc1a0cba000)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.4/baseapp/abci.go:925 +0x24c\ngithub.com/cosmos/cosmos-sdk/server.cometABCIWrapper.FinalizeBlock(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.4/server/cmt_abci.go:44\ngithub.com/cometbft/cometbft/abci/client.(*unsyncLocalClient).FinalizeBlock(0xc057a78488?, {0x5627a30?, 0x77393c0?}, 0xc0?)\n\tgithub.com/cometbft/cometbft@v0.38.5/abci/client/unsync_local_client.go:137 +0x26\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc00dae1110, {0x5627a30, 0x77393c0}, 0x1?)\n\tgithub.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:104 +0x170\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc00bb4b90a, 0x6}}, {0xc00bb4b9a0, 0xe}, 0x1, 0x10bf1bf, {{0xc2f987ada0, ...}, ...}, ...}, ...)\n\tgithub.com/cometbft/cometbft@v0.38.5/state/execution.go:226 +0x837\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc001353180, 0x10bf1c0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:1833 +0xb7d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc001353180, 0x10bf1c0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:1744 +0x349\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:1679 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc001353180, 0x10bf1c0, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:1717 +0xcd0\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc001353180, 0xc2be783ee0, {0xc002fa8150, 0x28})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2371 +0x1be5\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc001353180, 0xc2be783ee0, {0xc002fa8150?, 0xc057a79c08?})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:2123 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc001353180, {{0x55f3740, 0xc1a08187c8}, {0xc002fa8150, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc001353180, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 69\n\tgithub.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c\n"
```

### Anything else we need to know

Tests were conducted with different versions of Cosmos-SDK (0.50/0.47/0.40), all with the same result. This issue causes inconsistencies in the application, making it difficult to maintain system integrity and reliability.

**Comment by cason** [comment]
This version `v0.34.1` is not even tracked on this repository. It belongs to the old https://github.com/tendermint/tendermint repository. The first version of the `0.34.x` family maintained by this repository is `v0.34.27`. Can you confirm that the same error occurs with that version?

**Comment by lucaslopezf** [comment]
> This version `v0.34.1` is not even tracked on this repository. It belongs to the old https://github.com/tendermint/tendermint repository. The first version of the `0.34.x` family maintained by this repository is `v0.34.27`. Can you confirm that the same error occurs with that version?

Sorry, that version corresponds to cosmos-sdk version v0.40. I have tried with the latest version and it still occurs, inclusive with [v1.0.0-rc1](https://github.com/cometbft/cometbft/releases/tag/v1.0.0-rc1)

**Comment by andynog** [comment]
I think this might be a valid point based on the referenced PRs in the SDK. We need to test and see why not all services are stopped and the node process exits.

By the way, just to double check, are you using a single binary (CometBFT+App) ?

Based on this [comment](https://github.com/cosmos/cosmos-sdk/issues/20745#issuecomment-2273991047) looks like the `p2p` and `RPC` services still run in this case. 

We need to do some further investigation and testing, but notice some [code](https://github.com/cometbft/cometbft/blob/5e4ab3c747558cdea85cdd3fc320fe6b5c363930/proxy/multi_app_conn.go#L161) related to a kill switch in the proxy app when the client crash that seems these two services are not part of that, not sure it is related but one thing to investigate.

Not sure yet, if this is on the SDK side or CometBFT. Needs some testing.

**Comment by mmsqe** [comment]
Not sure if we could add a Stop function in [unsyncLocalClient](https://github.com/cometbft/cometbft/blob/54098b0c19099a38d2ce43aa30e6aee4c3f90978/abci/client/unsync_local_client.go) and [Application](https://github.com/cometbft/cometbft/blob/54098b0c19099a38d2ce43aa30e6aee4c3f90978/abci/types/application.go#L11), so cometbft call `cs.blockExec.StopProxyApp(ctx)` on [onExit](https://github.com/cometbft/cometbft/blob/54098b0c19099a38d2ce43aa30e6aee4c3f90978/internal/consensus/state.go#L796) to notify sdk when recover.

**Comment by julienrbrt** [comment]
Is there any progress on this? That would be useful.

**Comment by Tyagiquamar** [comment]
I'd like to take this if it's still available. I reproduced the issue on current main at 3bd679a20b154bcba63aae7edb13faa673103e38 and don't see an in-flight fix. I'll add a focused regression first and keep the change scoped to node. Is anyone already working on it?
